name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Send PR Data to CodeGen AI Reviewer
        run: |
          curl -X POST https://codegen-r62f.onrender.com/webhook \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.CODEGEN_API_KEY }}" \
          -d '{
                "repository": "${{ github.repository }}",
                "pull_request": {
                  "number": "${{ github.event.pull_request.number }}",
                  "diff_url": "${{ github.event.pull_request.diff_url }}"
                }
              }'
